### ISSUE TITLE
Import statements not working on local machine

### ISSUE THREAD

**Issue by pprathameshmore** [JupiterOne/security-policy-builder#111]
I am trying to execute the source on my Windows 10 machine. Seems like I getting errors around import statements. I am not aware of these new aliases for imports. Could you please tell me how to fix this issue?

![image](https://user-images.githubusercontent.com/17108186/113297856-c8113080-9318-11eb-84c8-4dc0d5b9d428.png)

Thanks

**Comment by aiwilliams** [comment]
Hi @pprathameshmore. Please review the `package.json` and be sure you have all the dependencies installed, particularly TypeScript and Babel and whatnot, and see if `yarn compile` works.

**Comment by pprathameshmore** [comment]
@aiwilliams Now it's working. Thanks.

**Comment by pprathameshmore** [comment]
@aiwilliams I am getting the same issue again. Could you tell me commands to configure Babel for this project?
and I am trying this as a package in my other project.

![image](https://user-images.githubusercontent.com/17108186/114008648-188c0f00-9880-11eb-8817-c4ef872e910a.png)

But when I tried to import in my other project. It throws an error.

![image](https://user-images.githubusercontent.com/17108186/114008571-00b48b00-9880-11eb-8bfa-4265e30394d1.png)
