### ISSUE TITLE
Is it possible to stop the generation of HIPAA related documents?

### ISSUE THREAD

**Issue by charlesgreen** [JupiterOne/security-policy-builder#97]
psp 4.0

I found that by updating the `config.json` I was able to most references to HIPAA.
The only 2 files are still automatically generated. It is possible to disable them from generating or remove them before pushing them to Confluence?

```
docs/hipaa-mapping.md
docs/hipaa-baa.md
```

I've tried updating the references in `config.json `

```
    {
      "id": "ref-hipaa-baa",
      "file": "ref/hipaa-baa.md",
      "name": "HIPAA Business Associate Agreement",
      "applicable": false,
      "adopted": false
    },
    {
      "id": "ref-hipaa-mapping",
      "file": "ref/hipaa-mapping.md",
      "name": "HIPAA Controls Mapping",
      "applicable": false,
      "adopted": false
    },
```

**Comment by erichs** [comment]
I'm unable to duplicate this locally. Can you confirm that you're not seeing the result of previous builds? (i.e. make sure `docs` directory is removed, then build again.

**Comment by charlesgreen** [comment]
Thank you @erichs. My mistake. I didn't remove the docs folder before rebuilding.
